### ISSUE TITLE
Process `db_search_comet (1)` terminated with an error exit status (9)

### ISSUE THREAD

**Issue by Zethson** [Leon-Bichmann/MHCquant#14]
`nextflow run nf-core/mhcquant --mzmls 'https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_1_A_1.mzML' 'https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_1_B_1.mzML' 'https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_2_A_1.mzML' 'https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_2_B_1.mzML' --fasta 'https://github.com/nf-core/test-datasets/raw/mhcquant/test.fasta' --alleles 'https://github.com/nf-core/test-datasets/raw/mhcquant/alleles.tsv' --vcf 'https://github.com/nf-core/test-datasets/raw/mhcquant/GRIAFFLKY_snpeff.vcf' --include_proteins_from_vcf --run_prediction --max_cpus 2 --max_memory 6.GB  -profile standard,docker
`

as well as 

`nextflow run nf-core/mhcquant -profile test, docker`

return:

ERROR ~ Error executing process > 'db_search_comet (1)'

Caused by:
  Process `db_search_comet (1)` terminated with an error exit status (9)

Command executed:

  CometAdapter  -in MM15_Melanom_1_A_1.mzML \
                -out MM15_Melanom_1_A_1.idXML \
                -threads 2 \
                -database test_added_vcf_decoy.fasta \
                -precursor_mass_tolerance 5 \
                -fragment_bin_tolerance 0.02 \
                -fragment_bin_offset 0 \
                -num_hits 1 \
                -digest_mass_range 800:2500 \
                -max_variable_mods_in_peptide 3 \
                -allowed_missed_cleavages 0 \
                -precursor_charge 2:3 \
                -activation_method ALL \
                -use_NL_ions true \
                -variable_modifications 'Oxidation (M)' \
                -fixed_modifications  \
                -enzyme 'unspecific cleavage' \
                -spectrum_batch_size 500

Command exit status:
  9

Command output:
  Version 2.4.0-HEAD-2018-10-26 of CometAdapter is available at www.OpenMS.de
  Comet is writing the default parameter file...
  Executing: comet.exe
  Executed comet.exe successfully!
  Progress of 'loading spectra list':
  
  -- done [took 0.70 s (CPU), 0.37 s (Wall)] -- 
  Progress of 'loading chromatogram list':
  
  -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
  FATAL: External invocation of comet.exe failed. Standard output and error were:
  <Executing: comet.exe> occurred 2 times
   Comet version "2016.01 rev. 3"
  
  
  
  11
  CometAdapter took 0.74 s (wall), 0.84 s (CPU), 0.03 s (system), 0.81 s (user).

Command wrapper:
  Version 2.4.0-HEAD-2018-10-26 of CometAdapter is available at www.OpenMS.de
  Comet is writing the default parameter file...
  Executing: comet.exe
  Executed comet.exe successfully!
  Progress of 'loading spectra list':
  
  -- done [took 0.70 s (CPU), 0.37 s (Wall)] -- 
  Progress of 'loading chromatogram list':
  
  -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
  FATAL: External invocation of comet.exe failed. Standard output and error were:
  <Executing: comet.exe> occurred 2 times
   Comet version "2016.01 rev. 3"
  
  
  
  11
  CometAdapter took 0.74 s (wall), 0.84 s (CPU), 0.03 s (system), 0.81 s (user).

Work dir:
  /home/zeth/nextflow_projects/MHCquant/work/b3/0a2e715125fc6794463922d093d38b

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details

**Comment by Leon-Bichmann** [comment]
Hey, 
strange.. did you specify a specific revision eg. --r 1.2.6 ?

**Comment by Zethson** [comment]
No. Any version specific version that you want me to test?

**Comment by Leon-Bichmann** [comment]
ok I think it is the whitespace between the test and docker profile

try:
```
nextflow run nf-core/mhcquant -profile test,docker -r 1.2.6
```

**Comment by Zethson** [comment]
Same result.

**Comment by Leon-Bichmann** [comment]
ok hmm.. for me its working, can you post the nf-core log that is printed on the screen?

**Comment by Zethson** [comment]
(base) [zeth@master MHCquant]$ nextflow run nf-core/mhcquant -profile test,docker -r 1.2.6
N E X T F L O W  ~  version 19.01.0
Launching `nf-core/mhcquant` [gigantic_poisson] - revision: 124cbbe5a0 [1.2.6]
=======================================================
                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~'
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

nf-core/mhcquant v1.2.6"
=======================================================
Pipeline Name  : nf-core/mhcquant
Pipeline Version: 1.2.6
Run Name       : gigantic_poisson
mzMLs          : [https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_1_A_1.mzML, https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_1_B_1.mzML, https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_2_A_1.mzML, https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_2_B_1.mzML]
Fasta Ref      : [https://github.com/nf-core/test-datasets/raw/mhcquant/test.fasta]
Predictions    : false
SubsetFDR      : false
Alleles        : [https://github.com/nf-core/test-datasets/raw/mhcquant/alleles.tsv]
Variants       : [https://github.com/nf-core/test-datasets/raw/mhcquant/GRIAFFLKY_snpeff.vcf]
Centroidisation: false
Max Memory     : 6 GB
Max CPUs       : 2
Max Time       : 2d
Output dir     : ./results
Working dir    : /home/zeth/nextflow_projects/MHCquant/work
Container Engine: docker
Container      : nfcore/mhcquant:1.2.6
Current home   : /home/zeth
Current user   : zeth
Current path   : /home/zeth/nextflow_projects/MHCquant
Script dir     : /home/zeth/.nextflow/assets/nf-core/mhcquant
Config Profile : test,docker
=========================================
[warm up] executor > local
[ce/f2cec0] Submitted process > output_documentation
[bd/3f924f] Submitted process > generate_decoy_database (1)
[c4/78d6e6] Submitted process > db_search_comet (1)
[28/42b4d5] Submitted process > db_search_comet (3)
ERROR ~ Error executing process > 'db_search_comet (1)'

Caused by:
  Process `db_search_comet (1)` terminated with an error exit status (9)

Command executed:

  CometAdapter  -in MM15_Melanom_1_B_1.mzML \
                -out MM15_Melanom_1_B_1.idXML \
                -threads 2 \
                -database test_decoy.fasta \
                -precursor_mass_tolerance 5 \
                -fragment_bin_tolerance 0.02 \
                -fragment_bin_offset 0 \
                -num_hits 1 \
                -digest_mass_range 800:2500 \
                -max_variable_mods_in_peptide 3 \
                -allowed_missed_cleavages 0 \
                -precursor_charge 2:3 \
                -activation_method ALL \
                -use_NL_ions true \
                -variable_modifications 'Oxidation (M)' \
                -fixed_modifications  \
                -enzyme 'unspecific cleavage' \
                -spectrum_batch_size 500

Command exit status:
  9

Command output:
  Version 2.4.0-HEAD-2018-10-26 of CometAdapter is available at www.OpenMS.de
  Comet is writing the default parameter file...
  Executing: comet.exe
  Executed comet.exe successfully!
  Progress of 'loading spectra list':
  
  -- done [took 0.67 s (CPU), 0.68 s (Wall)] -- 
  Progress of 'loading chromatogram list':
  
  -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
  FATAL: External invocation of comet.exe failed. Standard output and error were:
  <Executing: comet.exe> occurred 2 times
   Comet version "2016.01 rev. 3"
  
  
  
  11
  CometAdapter took 1.08 s (wall), 0.79 s (CPU), 0.05 s (system), 0.74 s (user).

Command wrapper:
  Version 2.4.0-HEAD-2018-10-26 of CometAdapter is available at www.OpenMS.de
  Comet is writing the default parameter file...
  Executing: comet.exe
  Executed comet.exe successfully!
  Progress of 'loading spectra list':
  
  -- done [took 0.67 s (CPU), 0.68 s (Wall)] -- 
  Progress of 'loading chromatogram list':
  
  -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
  FATAL: External invocation of comet.exe failed. Standard output and error were:
  <Executing: comet.exe> occurred 2 times
   Comet version "2016.01 rev. 3"
  
  
  
  11
  CometAdapter took 1.08 s (wall), 0.79 s (CPU), 0.05 s (system), 0.74 s (user).

Work dir:
  /home/zeth/nextflow_projects/MHCquant/work/c4/78d6e6d87ee9c42702e8902fb9c0cb

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details


Pretty much the same without any helpful additional information is in .nextflow.log

**Comment by Leon-Bichmann** [comment]
```
N E X T F L O W  ~  version 18.10.1
Launching `nf-core/mhcquant` [ridiculous_ampere] - revision: 124cbbe5a0 [1.2.6]
=======================================================
                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~'
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

nf-core/mhcquant v1.2.6"
=======================================================
Pipeline Name  : nf-core/mhcquant
Pipeline Version: 1.2.6
Run Name       : ridiculous_ampere
mzMLs          : [https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_1_A_1.mzML, https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_1_B_1.mzML, https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_2_A_1.mzML, https://github.com/nf-core/test-datasets/raw/mhcquant/MM15_Melanom_2_B_1.mzML]
Fasta Ref      : [https://github.com/nf-core/test-datasets/raw/mhcquant/test.fasta]
Predictions    : false
SubsetFDR      : false
Alleles        : [https://github.com/nf-core/test-datasets/raw/mhcquant/alleles.tsv]
Variants       : [https://github.com/nf-core/test-datasets/raw/mhcquant/GRIAFFLKY_snpeff.vcf]
Centroidisation: false
Max Memory     : 6 GB
Max CPUs       : 2
Max Time       : 2d
Output dir     : ./results
Working dir    : /Users/bichmann/Projects/Replicate_Workflow/work
Container Engine: docker
Container      : nfcore/mhcquant:1.2.6
Current home   : /Users/bichmann
Current user   : bichmann
Current path   : /Users/bichmann/Projects/Replicate_Workflow
Script dir     : /anaconda2/envs/py36/share/nextflow/assets/nf-core/mhcquant
Config Profile : test,docker
=========================================
```

**Comment by Zethson** [comment]
My nextflow version is higher than yours. You're still on 18.10

**Comment by Leon-Bichmann** [comment]
Ok just tested it with nextflow 19 as well and it also works, that doesnt seem to be the problem.

Have you pulled the most recent docker image?

docker pull nfcore/mhcquant
nextflow pull nf-core/mhcquant

**Comment by Zethson** [comment]
I did have to pull the recent docker image, but the error is unfortunately persistent :/

**Comment by Leon-Bichmann** [comment]
ok lets take this to the nf-core slack. Hopefully it can be solved latest in the nextflow workshop next week!

**Comment by Zethson** [comment]
Reboot didn't help. I'm on it.

**Comment by Zethson** [comment]
I send you details in the mail, I will expand on this as soon as we know more.
The issue could be reproduced on another arch-based system. So I'm not the only one with this ;)

**Comment by Leon-Bichmann** [comment]
Thanks for spotting this bug, lets see if we can fix it like that.

**Comment by Zethson** [comment]
Fun fact: It works now on my Arch machine.

I still have no damn clue why.
